# SPDX-FileCopyrightText: 2025-2026 Pavel Zaitsau
# SPDX-FileCopyrightText: 2025-2026 Góra Print
# SPDX-License-Identifier: AGPL-3.0-or-later
"""OBJ/MTL file export utilities for 3D mesh data."""

import contextlib
import os
import tempfile
from collections.abc import Sequence
from pathlib import Path
from typing import TypedDict

import numpy as np
import numpy.typing as npt

# A face is three 1-based vertex indices, in the order written to the OBJ.
Face = tuple[int, int, int]


class _Material(TypedDict, total=False):
    """MTL material entry. `total=False` — every key is optional (only water has `d`)."""

    Ka: tuple[float, float, float]
    Kd: tuple[float, float, float]
    Ks: tuple[float, float, float]
    Ns: float
    d: float


class _Group(TypedDict):
    """One `g` block in the OBJ: a named face range with an optional material."""

    name: str
    material: str | None
    faces: list[Face]


class Mesh:
    """Simple mesh data container compatible with OBJ export."""

    # Define dtype compatible with numpy-stl format
    dtype = np.dtype(
        [
            ("normals", np.float32, (3,)),
            ("vectors", np.float32, (3, 3)),
            ("attr", np.uint16, (1,)),
        ]
    )

    def __init__(self, data_array: npt.NDArray[np.void]) -> None:
        """
        Initialize mesh from structured array.

        Args:
            data_array: Numpy structured array with 'vectors' field
        """
        # Store data in numpy-stl compatible format
        self.data = data_array

    @property
    def vectors(self) -> npt.NDArray[np.float32]:
        """Get mesh vectors for backward compatibility."""
        # Indexing a structured array by field name is typed as returning `Any`;
        # the dtype above pins this field to float32 (n_faces, 3, 3).
        vectors: npt.NDArray[np.float32] = self.data["vectors"]
        return vectors

    @vectors.setter
    def vectors(self, value: npt.ArrayLike) -> None:
        """Set mesh vectors for backward compatibility."""
        self.data["vectors"] = value


class OBJExporter:
    """Export mesh data to Wavefront OBJ format with material support."""

    def __init__(self) -> None:
        self.vertices: list[npt.NDArray[np.float32]] = []
        self.groups: list[_Group] = []

    def add_mesh(self, mesh_data: Mesh, group_name: str, material_name: str | None = None) -> None:
        """
        Add a mesh to the exporter.

        Args:
            mesh_data: numpy-stl mesh object or mesh data with .vectors attribute
            group_name: Name for this mesh group (e.g., 'terrain', 'track', 'water')
            material_name: Optional material name to apply
        """
        # Extract vertices from mesh.vectors (shape: [n_faces, 3, 3])
        # Each face has 3 vertices, each vertex has 3 coordinates (x, y, z)
        vertices_start = len(self.vertices)

        for face in mesh_data.data["vectors"]:
            for vertex in face:
                self.vertices.append(vertex)

        # Create faces (groups of 3 vertex indices)
        n_vertices_added = len(self.vertices) - vertices_start
        n_faces = n_vertices_added // 3

        faces_for_group: list[Face] = []
        for i in range(n_faces):
            base_idx = vertices_start + i * 3
            # OBJ format uses 1-based indexing.
            # The writer below swaps Y and Z (model space is Z-up, OBJ is Y-up).
            # Swapping two axes is a mirror, so the corner order has to be
            # reversed with it — otherwise every face keeps its old winding in a
            # flipped frame and the whole model exports inside out (summit faces
            # pointing down, negative volume, "flipped normals" in slicers).
            faces_for_group.append((base_idx + 1, base_idx + 3, base_idx + 2))

        self.groups.append(
            {"name": group_name, "material": material_name, "faces": faces_for_group}
        )

    def save(self, filepath: str | Path, generate_mtl: bool = True) -> None:
        """
        Save the mesh to an OBJ file.

        Args:
            filepath: Output OBJ file path
            generate_mtl: Whether to generate accompanying MTL file
        """
        base_path = Path(filepath)
        obj_path = base_path.with_suffix(".obj")
        mtl_path = base_path.with_suffix(".mtl")
        has_materials = generate_mtl and any(g.get("material") for g in self.groups)

        # Write OBJ file atomically (temp file + rename) to ensure complete overwrite
        dir_ = obj_path.parent
        with tempfile.NamedTemporaryFile(
            "w", encoding="utf-8", dir=dir_, delete=False, suffix=".obj.tmp"
        ) as tmp:
            tmp_obj_path = tmp.name
            tmp.write("# Generated by 3D Terrain Router\n")
            tmp.write(f"# Vertices: {len(self.vertices)}\n")
            tmp.write(f"# Faces: {sum(len(g['faces']) for g in self.groups)}\n\n")

            if has_materials:
                tmp.write(f"mtllib {mtl_path.name}\n\n")

            # Write vertices
            # OBJ format uses Y as up axis, so swap Y and Z from our coordinate system
            # Our system: X=left-right, Y=front-back, Z=up-down
            # OBJ system: X=left-right, Y=up-down, Z=front-back
            for vertex in self.vertices:
                tmp.write(f"v {vertex[0]:.6f} {vertex[2]:.6f} {vertex[1]:.6f}\n")

            tmp.write("\n")

            for group in self.groups:
                tmp.write(f"g {group['name']}\n")
                if group.get("material"):
                    tmp.write(f"usemtl {group['material']}\n")

                for face in group["faces"]:
                    tmp.write(f"f {face[0]} {face[1]} {face[2]}\n")

                tmp.write("\n")

        # The rename is what makes the write atomic. Nothing else removes the
        # temp file, so a full disk or an interrupt used to leave `tmp*.obj.tmp`
        # beside the model for good.
        try:
            os.replace(tmp_obj_path, obj_path)
        except OSError:
            with contextlib.suppress(OSError):
                os.unlink(tmp_obj_path)
            raise

        # Write MTL file atomically if requested
        if has_materials:
            self._write_mtl(mtl_path)

    def _write_mtl(self, mtl_path: Path) -> None:
        """Write material library file with default materials."""
        # Define default materials with nice colors
        materials: dict[str, _Material] = {
            "terrain": {
                "Ka": (0.4, 0.3, 0.2),  # Ambient - brown
                "Kd": (0.6, 0.45, 0.3),  # Diffuse - tan/brown
                "Ks": (0.1, 0.1, 0.1),  # Specular - low shine
                "Ns": 10.0,  # Shininess
            },
            "track": {
                "Ka": (0.5, 0.0, 0.0),  # Ambient - dark red
                "Kd": (0.9, 0.1, 0.1),  # Diffuse - bright red
                "Ks": (0.3, 0.3, 0.3),  # Specular
                "Ns": 30.0,
            },
            "water": {
                "Ka": (0.0, 0.3, 0.6),  # Ambient - bright blue
                "Kd": (0.1, 0.5, 0.9),  # Diffuse - vibrant blue
                "Ks": (0.8, 0.8, 0.8),  # Specular - very shiny
                "Ns": 100.0,  # Very shiny water surface
                "d": 0.9,  # Slight transparency
            },
        }

        # Collect unique materials used in this export
        used_materials = set()
        for group in self.groups:
            if group.get("material"):
                used_materials.add(group["material"])

        with tempfile.NamedTemporaryFile(
            "w", encoding="utf-8", dir=mtl_path.parent, delete=False, suffix=".mtl.tmp"
        ) as tmp:
            tmp_mtl_path = tmp.name
            tmp.write("# Material library for 3D Terrain Router\n\n")

            for mat_name in used_materials:
                if mat_name in materials:
                    mat = materials[mat_name]
                    tmp.write(f"newmtl {mat_name}\n")
                    tmp.write(f"Ka {mat['Ka'][0]:.6f} {mat['Ka'][1]:.6f} {mat['Ka'][2]:.6f}\n")
                    tmp.write(f"Kd {mat['Kd'][0]:.6f} {mat['Kd'][1]:.6f} {mat['Kd'][2]:.6f}\n")
                    tmp.write(f"Ks {mat['Ks'][0]:.6f} {mat['Ks'][1]:.6f} {mat['Ks'][2]:.6f}\n")
                    tmp.write(f"Ns {mat['Ns']:.1f}\n")
                    if "d" in mat:
                        tmp.write(f"d {mat['d']:.6f}\n")  # Transparency (dissolve)
                    tmp.write("illum 2\n")  # Illumination model: color, ambient, diffuse, specular
                    tmp.write("\n")

        try:
            os.replace(tmp_mtl_path, mtl_path)
        except OSError:
            with contextlib.suppress(OSError):
                os.unlink(tmp_mtl_path)
            raise


def save_mesh_obj(
    mesh_data: Mesh,
    filepath: str,
    group_name: str = "mesh",
    material_name: str | None = None,
    generate_mtl: bool = True,
) -> None:
    """
    Save a single mesh to OBJ format.

    Args:
        mesh_data: numpy-stl mesh object or mesh data with .data['vectors'] attribute
        filepath: Output file path (.obj extension will be added if missing)
        group_name: Name for the mesh group
        material_name: Optional material name (e.g., 'terrain', 'track', 'water')
        generate_mtl: Whether to generate MTL file with materials
    """
    exporter = OBJExporter()
    exporter.add_mesh(mesh_data, group_name, material_name)
    exporter.save(filepath, generate_mtl=generate_mtl)


def save_combined_mesh_obj(
    # Sequence, not list: `list` is invariant, so a caller's
    # `list[tuple[Mesh, str, str]]` would not match a `str | None` material.
    mesh_parts: Sequence[tuple[Mesh, str, str | None]],
    filepath: str,
    generate_mtl: bool = True,
) -> None:
    """
    Save multiple meshes to a single OBJ file with groups and materials.

    Args:
        mesh_parts: List of tuples: [(mesh_data, group_name, material_name), ...]
        filepath: Output file path
        generate_mtl: Whether to generate MTL file
    """
    exporter = OBJExporter()

    for mesh_data, group_name, material_name in mesh_parts:
        exporter.add_mesh(mesh_data, group_name, material_name)

    exporter.save(filepath, generate_mtl=generate_mtl)
